### ISSUE TITLE
MASSIVE TYPO

### ISSUE THREAD

**Issue by AnthonyRobertson17** [AntonNguyen/nonsense#2]
@AntonNguyen @minichate Someone PLEASE think of the CHILDREN!!!!!

https://github.com/AntonNguyen/nonsense/blob/master/nonsense/task.py#L122

AND

https://github.com/AntonNguyen/nonsense/blob/master/nonsense/task.py#L126

Double the typo double the shame 😞

**Comment by AntonNguyen** [comment]
Sorry, can't reproduce.

**Comment by g--** [comment]
I'm getting this problem too! Has anyone found a work-around?? Help!??

**Comment by g--** [comment]
https://xkcd.com/583/
